title: Nicolas M. | Computer Science ePortfolio
description: A portfolio documenting my growth and development throughout my computer science program.
url: "https://NicM-8bit.github.io"
baseurl: ""

theme: jekyll-theme-minimal
